name: Build and Push API Image.

on:
  push:
    branches:
      - 'staging'

permissions:
  id-token: write
  contents: read

jobs:
  define-params:
    runs-on: ubuntu-latest
    outputs:
      app_name: circulation-supply-api
      image_tag: ${{ github.sha }}
    steps:
      - run: echo "Exposing params"

  ecr-image-build:
    runs-on: ubuntu-latest
    needs: [define-params]
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -f ./dockerfiles/api.Dockerfile -t $REGISTRY/circulation-supply-api:${{ github.sha }} .
          docker push $REGISTRY/circulation-supply-api:${{ github.sha }}

  update-helm-tag:
    needs: [define-params, ecr-image-build]
    uses: ./.github/workflows/aws-reusable-helm-tag-update.yml
    with:
      app_name: ${{ needs.define-params.outputs.app_name }}
      helm_file_path: "story-helm/circulation-supply/circulation-supply-api/use1-stage.yaml"
      image_tag: ${{ needs.define-params.outputs.image_tag }}
    secrets:
      helm_repo_token: ${{ secrets.HELM_REPO_TOKEN }}
